### ISSUE TITLE
Search/request for wavelength range in refractiveindex database

### ISSUE THREAD

**Issue by domna** [MarJMue/Berreman4x4#102]
Problem: There is no convenient way to get the wavelength range from the rii database

Solution: Convenient request/searching/filtering for a specific material in a specific wavelength range. For example, there could be additional parameters to denote min/max which narrow down the selection.

**Comment by MarJMue** [comment]
This is quite simple to achieve. we just need to regex the range from the library.yml file. I just had no time to do it in the first iteration of the database.
