### ISSUE TITLE
Wrong polynomial parameter in refractiveindex info parser?

### ISSUE THREAD

**Issue by domna** [MarJMue/Berreman4x4#109]
Hey @MarJMue,

I'm playing around with the reading of the rii database and I'm confused by the following snippet:
https://github.com/PyEllips/pyElli/blob/efbc94edcad957db169678b670d100059c7c6656/src/elli/database/refractive_index_info.py#L279-L280

should it not just be `poly.add(f_i, e_i)` instead of `poly.add(f_i / 1e3**e_i, e_i)`? Or am I getting something wrong?

Here is the implementation we have:
https://github.com/PyEllips/pyElli/blob/e311b242a33fb053ef9fe8115b025c9dd46d23c3/src/elli/dispersions/polynomial.py#L27-L30

And the formula at [rri](https://refractiveindex.info/database/doc/Dispersion%20formulas.pdf) is:
<img width="990" alt="Bildschirm­foto 2023-01-25 um 17 28 15" src="https://user-images.githubusercontent.com/1014422/214619804-0fbcd9d1-e698-46f4-93ff-093fe34fe0ad.png">

**Comment by MarJMue** [comment]
Maybe i got unit conversions wrong again, but i thought we need to calculate `f*(lambda)**e = f*(1e3*um)**e = f * 1e3**e * um**e`

**Comment by domna** [comment]
Ah yes, I forgot about this completely. Because rii is operating in um and we are in nm. Makes sense to me now, I was just confused by the `**e_i`, but this is because the unit for each parameter is different. Thanks for clarifying.

**Comment by MarJMue** [comment]
Yes i missed it at first too, but found it while testing against the website in the unittest for the rii database.

**Comment by MarJMue** [comment]
Maybe we should add more inline comments, about stuff like this...

**Comment by domna** [comment]
> Maybe we should add more inline comments, about stuff like this...

Could be helpful here, yes. I also like using helper functions to explain what's happening, e.g. `um2nm` or so for this case here... it creates a little bit more code but often times its a lot nicer to read.

**Comment by domna** [comment]
But I think it's also not too bad here. I just was too focussed that I forgot about the um - nm conversion...
