### ISSUE TITLE
Broken pypi README and docs

### ISSUE THREAD

**Issue by domna** [MarJMue/Berreman4x4#116]
Problems:

- [x] pyElli logo not displayed correctly in pypi
- [x] Dispersions parameter have an appended `::`
- [x] The second function in the documentation of the Psuedo Dielectric Function is not displayed correctly

After fixing:

- [x] ~~Retrigger `v0.15.1` release action to update the pages.~~ Does not work without increasing the version

**Comment by MarJMue** [comment]
Ah they do not understand the light/dark theming from Github.

**Comment by domna** [comment]
The double colon is not displayed for me when I build locally with `make html`. Probably comes from another sphinx version or so (Edit: Tried with `sphinx==5.3.0` locally and removal of all cached files, still no double colon).

**Comment by domna** [comment]
The colon seems to have to do sth with the docutils version: https://github.com/sphinx-doc/sphinx/issues/10594

However, I couldn't manage to reproduce this error locally. Thus I just added the css fix mentioned in the issue above, which works fine in both cases.

**Comment by domna** [comment]
Logo should be fixed. Hopefully it works on pypi, too

**Comment by domna** [comment]
This still doesn't work on pypi...

**Comment by domna** [comment]
@MarJMue Is it fine with you if we'd remove the logo from the README? I don't really know how we can implement it properly to work in gh, gh app and pypi.

**Comment by MarJMue** [comment]
Feel free to remove the logo, or replace it with a single one without transparency. Your call.

**Comment by domna** [comment]
I just implemented the dark image. My previous version was using the browsers dark oder light setting anyways and not the one from gh. Anyways, that should now also work for pypi.
