### ISSUE TITLE
pyElli and lmfit

### ISSUE THREAD

**Issue by rugfri** [MarJMue/Berreman4x4#125]
Hi all,

is it possible to use run a fit using a fitting algorithm different from the lmfit default least-squares?
lmfit does implement various algorithm for optimization, but it is not clear to me how such option should be passed.

Thanks!

**Comment by domna** [comment]
Yes, you can pass a method argument to the fit model class, you can find this in the documentation [here](https://pyelli.readthedocs.io/en/stable/plot.html#elli.fitting.decorator_psi_delta.FitRho.fit)

In the [basic example](https://pyelli.readthedocs.io/en/stable/auto_examples/plot_01_basic_usage.html#fit-and-plot-fit-results) you just have to change `model.fit()` to `model.fit(method='your-lmfit-method')`. The string is directly passed to lmfit and therefore you can use any method from lmfit there.

Currently, it is not possible to use this directly with the `@fit` decorator and the Fit button. This is, however, easy to implement so if you find this helpful I can quickly add this.

**Comment by domna** [comment]
Hi @rugfri 

I added to possibility to pass keyword arguments via the `@fit` decorator to lmfit. You can then use `@fit(...., method='bfgs')` to use the `bfgs` fitting method. Besides you can use any other keyworded argument to pass it to lmfits `minimze` function. You can use this in a dev install as soon as #129 is merged.
