### ISSUE TITLE
Wrong order in SellmeierCustomExponent?

### ISSUE THREAD

**Issue by domna** [MarJMue/Berreman4x4#126]
@MarJMue I think according to this
https://github.com/PyEllips/pyElli/blob/fb8dd83fae9ddfe6fc4fde83d26023a5f65fe5e8/src/elli/dispersions/sellmeier_custom.py#L29

the order in the SellmeierCustom function should not be
https://github.com/PyEllips/pyElli/blob/567262cb3c68f6f1fbedff5fb493ac67fb0216f2/src/elli/database/refractive_index_info.py#L409-L410

but rather `sell.add(a_i, b_i, e1_i, e2_i)` (swap of `e1_i` and `b_i`).

Do you agree or am I missing something?

**Comment by MarJMue** [comment]
You are completely right. I will fix it quickly...
