### ISSUE TITLE
Solver2x2 does not work with active media

### ISSUE THREAD

**Issue by MarJMue** [MarJMue/Berreman4x4#130]
As explained in Byrnes' [Paper](https://arxiv.org/pdf/1603.02720.pdf) (appendices C and D) the fresnel method can not handle active media that exhibit gain. 

We should either check the inputs or give at least a warning if n>0 and k<0.

**Comment by domna** [comment]
I see. Thank you for researching this!

I think we can just show a warning or even raise an exception for this case. We should then refer to the Solver4x4, because I assume that it can handle gain correctly, right?

**Comment by MarJMue** [comment]
As far as i can tell 4x4 should work with active media, until the algorithm breaks down due to overflow errors.

**Comment by domna** [comment]
Ok, then I would say that Solver2x2 is just not suitable for gain media and we should let it fail for negative k and refer to Solver4x4. Agreed?

**Comment by MarJMue** [comment]
👍
