### ISSUE TITLE
General search in RII database

### ISSUE THREAD

**Issue by domna** [MarJMue/Berreman4x4#139]
I just had a look at the RII database and I thought it may be nice to have a function just called search to search in any book or page. The problem is that currently there is search_book and search_page, which users don't really know what it represents so it is hard to decide which one to use.

**Comment by MarJMue** [comment]
yeah the names of the functions are pretty bad. i have no good idea how to name them more verbose. As:

> For inorganic and organic materials Book uses the sum formula of the compound and Page is an identifier of the author of the publication. In the case of glasses, book is the manufacturer and page the name of the glass.

Maybe you are right and we should converge all three usefull fields into one search.

**Comment by domna** [comment]
Yeah these book and page identifiers are pretty confusing. I never really understand where I should search in.
Anyways, I think if we'd just ignore what is happening for books and pages and just search for everything then it'll be fine.
