### ISSUE TITLE
Numpy 2.0.0 support

### ISSUE THREAD

**Issue by domna** [MarJMue/Berreman4x4#175]
Numpy just released [version 2](https://numpy.org/devdocs/release/2.0.0-notes.html).
We should check compatibility and follow the appropriate migrations: https://numpy.org/devdocs/numpy_2_0_migration_guide.html#numpy-2-migration-guide

**Comment by domna** [comment]
@MarJMue When I adapt this I would also switch to ruff (because numpy 2 provides a linting plugin for it https://numpy.org/devdocs/numpy_2_0_migration_guide.html#ruff-plugin + it's fast + it can lint and format. It effectively replaces black and pylint)  and uv (because it's extremely fast compared to simple `pip compile`). Fine for you?

**Comment by MarJMue** [comment]
Sure feel free to do that. I'm already using ruff privately and wanted to try out uv as well.
