### ISSUE TITLE
Error with RII database in pyelli 0.21.0

### ISSUE THREAD

**Issue by mrtnrb** [MarJMue/Berreman4x4#195]
Hello,

using in pyelli 0.21.0 the command:
`RII = elli.db.RII()`

returns:
ModuleNotFoundError: No module named 'elli.database.refractiveindexinfo-database'

going back to pyelli 0.20.0 works as expected.

Can you have a look into that?

Best
Martin

**Comment by domna** [comment]
Hey @mrtnrb,

I'll have a look. I think I already know what the problem is. Our packaging workflow is missing the refractiveindex.info submodule. I'll check, verify and (hopefully) update pyElli in the evening.

Until then you should be able to use
```sh
pip install git+https://github.com/PyEllips/pyElli.git
```
to work with the latest version

**Comment by MarJMue** [comment]
You were completely right, I took the freedom and fixed it swiftly.
