### ISSUE TITLE
Müller Matrix Calculation has wrong signs

### ISSUE THREAD

**Issue by MarJMue** [MarJMue/Berreman4x4#26]
Last row of matrix elements has the inversed sign for isotropic materials.

![mm bug](https://user-images.githubusercontent.com/49639740/134860256-0c047335-ea3e-41bf-9e5f-ded290690055.png)

Anisotropic samples need to be investigated to get insight into other elements.

**Comment by domna** [comment]
Könnte die Sortierung und Normierung der Eigenvektoren ein Problem sein?
So wie ich das sehe wird zuerst nach Re und Im sortiert und dann einfach nach Ey, ich sehe aber ansonsten häufig, dass zuerst zuerst + und - Moden unterschieden werden und dann die Relation Ex**2 / (Ex**2 + Ez**2) verwendet wird zusammen mit der Normierung Ex1 = 1, Ex1 = -1, Ez3 = Ez4 = 1 (jeweils für die Eigenvektoren Ei). Siehe dazu [hier](https://arxiv.org/pdf/1707.00462.pdf) und [hier](https://www.osapublishing.org/ao/abstract.cfm?uri=ao-27-7-1334).

Außerdem könnte es sein, dass die Sortierung zusammen bricht, weil real == 0 exakt abgefragt wird, was evtl. failed wenn da kleines numerisches Rauschen drauf ist.

Edit: Nee, vergiss es, den non-Iso Halfspace ruft er bei mir gar nicht auf und hat den Fehler trotzdem - muss also irgendwo anders stecken

**Comment by domna** [comment]
Ich denke der Fehler schlummert irgendwo in der Transformation zwischen Jones und Müller Matrix.
Wenn ich mir die T_ri Matrix raus hole, die den Wert

    jones_m = np.array([[0.25546072 + 0.12113279 * 1j, 0],
                        [0, -0.86769116 - 0.18306675 * 1j]], dtype=np.complex128)
hat und dann folgendermaßen transformiere

    mm = np.real(A @ np.kron(jones_m, np.conjugate(jones_m)) @ inv(A))
    mm / mm[0, 0]
bekomme ich die (hoffentlich) korrekte Matrix

    array([[ 1.        , -0.81546778,  0.        ,  0.        ],
           [-0.81546778,  1.        ,  0.        ,  0.        ],
           [ 0.        ,  0.        , -0.56291498, -0.13468117],
           [ 0.        ,  0.        ,  0.13468117, -0.56291498]])

Ich bin mir allerdings nicht sicher wie korrekt das ist auf m_00 zu normieren, aber ich glaube das passiert bei der S Matrix auch. Da muss ich nochmal im Berreman blättern. Auf jeden Fall versuche ich es mal so zu vektorisieren und schaue ob ich damit ein korrektes Ergebnis bekomme.
