### ISSUE TITLE
Examples in Documentation

### ISSUE THREAD

**Issue by domna** [MarJMue/Berreman4x4#46]
Ideally integrate the Jupiter Notebook Examples directly into the documentation, including plots (ideally interactively with plotly).

**Comment by domna** [comment]
https://blog.jupyter.org/jupyter-everywhere-f8151c2cc6e8

**Comment by domna** [comment]
https://sphinx-gallery.github.io/stable/getting_started.html

**Comment by domna** [comment]
@MarJMue I build an example gallery with sphinx gallery which is quite neat I think (see #68 ).
I also added the interface reflection example as a test (the examples parsed by sphinx-gallery are in the gallery subdirectory of the examples folder). Could you review the other examples you maintained? I think you have a better overview whether they are or which of them are useful.

From my side I also will add the TiO2 and SiO2 Müller Matrix examples. However, I haven't figured out how to display the ipywidgets box for the decorator in the sphinx-gallery files, yet. This I would like to find out before I'll put the other two examples as they somewhat need that displaying function.

**Comment by MarJMue** [comment]
Yes i think i want to an include one of the liquid crystal examples, because they show the capabilities for calculating inhomogeneous media.

**Comment by domna** [comment]
The major problems are solved and a great portion of examples are already available. Closing this issue, the remaining examples are handled within #69 .
