### ISSUE TITLE
Image to show the relations between Material, Structure, Experiment and Result

### ISSUE THREAD

**Issue by domna** [MarJMue/Berreman4x4#65]
Relates to #61

Something like this:
<img width="681" alt="Bildschirmfoto 2022-07-06 um 21 32 04" src="https://user-images.githubusercontent.com/1014422/177628457-f68ca8a5-0c34-41f5-8202-9600a1ed0a1c.png">

**Comment by domna** [comment]
@MarJMue What do you think of this relation image? Do you have critique or ideas for improvement?

We could also somehow show the shortcuts we're taking, e.g. without explicitly calling the experiment, because we use the standard settings in most cases. Or calling `.get_mat()` on the dispersions. Also we could somehow put the different subclasses in there (I just was not able to draw that beautifully ;)

**Comment by MarJMue** [comment]
I think your critique sums it up nicely. The most important short-cut would be skipping the experiment, which could be shown easily.

We could use boxes like:

```
--------------
Dispersion
--------------
Constant
Sellmeier
...
-------------
```

but it would get bloated really fast.

**Comment by domna** [comment]
Yeah I probably would pre-select where to show sub-classes, i.e. for dispersions I would leave them out, as I think this would look way to overcrowded. Also I think the dispersions are probably updated too frequently at some point, so the image would be out of sync quite fast. I thought more of static, i.e. the sub-classes of Materials, so people would know that there they should head to if they want to use anisotropic materials. Or that they could implement a z-variation in Structure.

Maybe just two additional images or side-graphs to show the relation inside Material and Structure?

I thought maybe we can try to implement this in [mermaid](https://mermaid-js.github.io/mermaid/#/) 🧜

**Comment by MarJMue** [comment]
I thought about something like mermaid too, but haven't tried it yet.
It even supports hyperlinks in boxes and would make an awesome simplified table of contents in the docs!

**Comment by domna** [comment]
Yes, maybe we even can write it in the rst file directly. So the image update will be easy as well 😎.

I experimented just a little with it. It seems quite nice and powerful. However, it not always produces the best looking graphs as its major goal is to provide fast and easy UML diagrams. So maybe at some point I would go for a nicely designed vector image (probably when we go for this JOSS paper) but I think mermaid is more than nice as the intermediate solution.

**Comment by MarJMue** [comment]
two more thoughts:
- Maybe a horizontal layout fits the more of the substructures.
- Show the possibility of generating multiple experiments and thus results

**Comment by domna** [comment]
I put a preliminary mermaid drawing in #68 . I did not integrate any of your suggestions yet and just redrew my hand-drawn image so it is all very much up for discussion. However, there was a mermaid sphinx plugin so we can edit it directly in the rst file :)

**Comment by domna** [comment]
I think most of the work is done and we can update the drawing on the fly if we want to improve it. Therefore closing this issue.
