### ISSUE TITLE
Add explanatory texts and examples to api documentation

### ISSUE THREAD

**Issue by domna** [MarJMue/Berreman4x4#69]
Each class should have a small introductory and explanatory text with an example on how to use them similar to the texts in the dispersions and solvers documentation.

The texts should be in the docstring of the respective classes.

**Comment by MarJMue** [comment]
ToDo for me:

- [x] Materials
- [x] Structure
- [x] Experiment
- [x] Result
- [x] Example: Liquid Crystals
- [x] Example: Bragg Mirror

**Comment by MarJMue** [comment]
Maybe we can also use the unit tests for the dispersions to generate static example plots (eps1/eps2 or n/k) for the documentation.
Nothing to urgent, but nice to have.

**Comment by domna** [comment]
Its possible to just use a plot directive in sphinx: https://matplotlib.org/sampledoc/extensions.html#inserting-matplotlib-plots

I would prefer it this way so the documentation and tests stay separated, because not separating it  may introduce headaches in the CI/CD

**Comment by MarJMue** [comment]
Sure. I was just thinking to recycle the default values you have already picked.

**Comment by domna** [comment]
Yeah, that's a good idea. The default values I chose are pretty arbitrary, though. I don't know if they would show a nice representation in plots. Anyways, we could put the values as a constant in the tests and just load it inside a python file in the docs which then gets picked up by the docs plot directive. Maybe we can just use the name of the section and give it to the function called in `.. plots::`, but I don't know if this is possible and how.

**Comment by domna** [comment]
I started a branch to play around with it: https://github.com/PyEllips/pyElli/tree/docs-dispersion-plots

**Comment by domna** [comment]
I really think it would be nice to have that! It would make the dispersions docs much nicer... maybe at some point we may also indicate the influence of certain parameters (like sentech and others do it in their manuals). Of course this is not possible for all dispersions (e.g. I would not know how to indicate that for a Cauchy model), but for the resonance based models it is possible (i.e. width and peak height for gaussian or lorentzian peaks etc.)

**Comment by MarJMue** [comment]
I think we have a good variety of examples now. More stuff will be added iteratively over time.
