### ISSUE TITLE
Proper dependency management

### ISSUE THREAD

**Issue by domna** [MarJMue/Berreman4x4#72]
Introduce better dependency management to not run in any dependency issues.
Either use [poetry](https://python-poetry.org), [pipenv](https://pypi.org/project/pipenv/) or specify version in requirements.txt with `pip freeze > requirements.txt` or add an additional requirements.freeze.txt.

This includes offering better install options for the optional fitting part. I think we should have something like `pip install pyElli[fitting]`.

**Comment by MarJMue** [comment]
Almost done here.

I had a look and i think we should move lmfit into plotting, because the fitting submodule only works with the plotting dependencies. And we could change the error message in the import of elli.fitting to hint at the pip install option. 

@domna  Or should we try to separate fitting and the interactive widget?

**Comment by domna** [comment]
I think we can keep fitting and interactive widget together as these are not so many dependencies and at least for me I most often just use them together. But it's a good approach to hint the pip install option 👍️

**Comment by domna** [comment]
@MarJMue I renamed the extra to fitting and put lmfit within there. I also updated the README to show how to install with the fitting extra as I think people most often want to use this capability.

**Comment by MarJMue** [comment]
> I think we can keep fitting and interactive widget together as these are not so many dependencies and at least for me I most often just use them together. But it's a good approach to hint the pip install option 👍️

I am totally fine with this. Fitting without visualizing the data is not very sensible. I just wanted to ask. 

Everything else is 'advanced' use from my view and everyone doing should be able to build their environment themself.
