### ISSUE TITLE
Don't use lambda as kwarg in dispersions

### ISSUE THREAD

**Issue by domna** [MarJMue/Berreman4x4#73]
In some dispersions lambda is used as kwarg to indicate a central wavelength (e.g. for LorentzLambda). Since this is the keyword for python lambda functions it is not possible to actually use it as a kwarg but just as an arg. Therefore all occurrences should be renamed.

**Comment by MarJMue** [comment]
@domna I have renamed it to lambda_r if you don't mind. it might be better distinguished form the evaluation wavelengths.

**Comment by domna** [comment]
Yeah, sure. Thanks for fixing it properly... somehow I only renamed the documentation 🤣
