### ISSUE TITLE
Rename math.py to prevent overwriting the builtin math namespace

### ISSUE THREAD

**Issue by MarJMue** [MarJMue/Berreman4x4#78]
Seems to be a possibility for name collision in jupyter kernels: [see this](https://github.com/microsoft/vscode-jupyter/wiki/Failure-to-start-Kernel-due-to-built-in-modules-being-overridden-by-user-code)

Maybe move the math stuff into the utility file.

**Comment by domna** [comment]
Good point... yeah maybe it's best to just move it into utils.
