### ISSUE TITLE
loading dielectric function from pandas dataframe

### ISSUE THREAD

**Issue by wlwatkins** [MarJMue/Berreman4x4#95]
I've never used SpectraRay, looking at the website mention in the documentation https://refractiveindex.info/ it is possible to download a csv. Is it possible to give this as a pandas to elli?

i guess it's around here in the basic example
```
sr = elli.TableSpectraRay("./")
Si = elli.IsotropicMaterial(sr.load_dispersion_table("Si_Schinke.mat"))
```

edit:

looking at https://pyelli.readthedocs.io/en/latest/_modules/elli/dispersions/table_epsilon.html#TableEpsilon i see i can give epsilon data, but i don't understand the format that's expected ? is it simply an array of complex number `ex: np.array([1+2j, 3+4j, 5+6j])`?
I'm going to test it right now, but have to admit, it must be the first time i'm using complex number as so in python (i usually split them in two r, and i vars)

**Comment by domna** [comment]
Hey @willmendil,

we actually supply an interface which automatically loads the csv file for you and generates a material you can use right away. See [here](https://pyelli.readthedocs.io/en/latest/database.html) for it's documentation. It is however not in the latest release yet, so you would need to install the package via git (either cloning + pip install . or via pip install git+...).

> looking at https://pyelli.readthedocs.io/en/latest/_modules/elli/dispersions/table_epsilon.html#TableEpsilon i see i can give epsilon data, but i don't understand the format that's expected ? is it simply an array of complex number ex: np.array([1+2j, 3+4j, 5+6j])?
I'm going to test it right now, but have to admit, it must be the first time i'm using complex number as so in python (i usually split them in two r, and i vars)

Yes, you can just pass a complex numpy array into this function. But I would suggest you use the reader we supply so you don't need to read and convert the file from refractiveindexinfo yourself.

Edit: One additional comment regarding spectraray. This is not a general loader for dispersion files (e.g. from refractiveindexinfo). It is a software supplied by the company sentech (which builds ellipsometers, too) and has it's own database format which can be read by our spectraray class, which we happen to use in the example (but we will probably change this to refractiveindex loading in the future to keep it more general).

**Comment by wlwatkins** [comment]
Ok, I get it, that's cool. Does it run a request to the website or has the database been downloaded and stored in the library?

**Comment by MarJMue** [comment]
The database is included in the library, as it enables offline work and is generally a bit easier to handle.
